import React from "react";
import {FC} from "react";

const curiosities: string[] = [
    'Sektor rolnictwa jest najbardziej intensywnym sektorem wodnym, a dostawa wody w rolnictwie jest coraz ważniejsza.',
    'Dane dotyczące nawadnianych gruntów rolnych i danych o średnich opadach ilustrują, w jaki sposób kraje uzyskują wodę do stosowania rolniczego.',
    'Prywatne przepływy finansowe - kapitał własny i dług - uwzględnienie większości finansów rozwoju.',
    'Pływy kapitałowe obejmują bezpośrednie inwestycje zagraniczne (FDI).',
    'Przepływy długu finansowanie wznosi się poprzez emisję obligacji, kredyty bankowe i kredyty dostawcy.',
    'Saldo płatności rejestruje transakcje gospodarki z resztą świata.',
    'Rachunki bilansu płatniczego są podzielone na dwie grupy: rachunek bieżący, który rejestruje transakcje w towarach, usługach, dochodach i transferach bieżących oraz rachunku kapitałowego i finansowego, które rejestruje transfery kapitałowe, nabycie lub usuwanie nie wyprodukowanych aktywów niezgodnychoraz transakcje w aktywach i zobowiązaniach finansowych.',
    'Wydatki na badania i rozwój (R & D) są kluczowym wskaźnikiem wysiłków rządowych i sektora prywatnego w celu uzyskania przewagi konkurencyjnej w nauce i technologii.',
    'Zdolność statystyczna jest zdolnością narodu gromadzenia, analizy i rozpowszechniania wysokiej jakości danych o swojej populacji i gospodarce.',
    'Statystyki jakości są niezbędne dla wszystkich etapów decyzyjnych opartych na dowodach, w tym: monitorowanie wskaźników społecznych i ekonomicznych, przydzielaniu reprezentacji politycznej i zasobów rządowych, prowadząc inwestycje w sektorze prywatnym, a także informowanie międzynarodowej społeczności dawcy do projektowania programu i preparat polityki.',
    'Ponieważ rozwój obejmuje wiele czynników - ekonomiczny, środowiskowy, kulturowy, edukacyjny i instytucjonalny - brak pojedynczej miary daje pełny obraz.',
    'Jednak łączne zarobki mieszkańców gospodarki, mierzone przez przychody narodowe brutto (DNB), jest dobrą miarą jej zdolności do zapewnienia dobrego samopoczucia jego ludu.',
    'W gospodarce rynkowej, gospodarstwo domowe, producent i rządowe wybory na temat alokacji zasobów wpływają względne ceny, w tym prawdziwy kurs, płace rzeczywiste, prawdziwe stopy procentowe i inne ceny w gospodarce.',
    'Stosunek ucznia-nauczyciela jest często stosowany do porównywania jakości szkolnej w różnych krajach, ale często jest słabo związany z uczeniem uczniów i jakością edukacji.',
    'Coraz częściej wykorzystywane jako podstawowy wskaźnik wydajności systemu edukacji odzwierciedla zasięg systemu edukacji i osiągnięcie edukacyjne studentów.',
    'Względne wysokie stężenie populacji dorosłych na danym poziomie edukacji odzwierciedla zdolność systemu edukacyjnego w odpowiednim poziomie edukacji.',
    'Osiągnięcie edukacyjne jest ściśle związane z umiejętnościami i kompetencjami ludności kraju i można go postrzegać jako proxy zarówno ilościowych, jak i jakościowych aspektów akcji kapitału ludzkiego.',
    'Wskaźnik netto w pierwszej klasie edukacji podstawowej wskazuje na poziom dostępu do edukacji podstawowej i zdolności systemu edukacji, aby zapewnić dostęp do edukacji podstawowej.',
    'Wysoka stawka wlotowa netto wskazuje wysoki stopień dostępu do edukacji podstawowej dla oficjalnych dzieci w wieku szkolnym w wieku szkolnym.',
    'Kohortowa stawka przeżycia mierzy moc gospodarstwa systemu edukacji i wydajność wewnętrzną.',
    'Udział wydatków rządowych na konkretny poziom edukacji pozwala na ocenę priorytetu rządu przypisuje do poziomu edukacji w stosunku do innych poziomów.',
    'Udział wydatków rządowych poświęconych edukacji pozwala na ocenę priorytetu rządowi przypisuje do edukacji w stosunku do innych inwestycji publicznych, a także zaangażowanie rządu w inwestowanie w rozwój kapitału ludzkiego.',
    'Kraje z młodszymi populacjami mogą wydawać więcej o edukację w odniesieniu do innego sektora, takich jak zdrowie lub ubezpieczenie społeczne oraz wice-versa.',
    'Odsetek wydatków rządowych na edukację do PKB jest przydatny do porównywania wydatków edukacyjnych między krajami i / lub w czasie w odniesieniu do wielkości ich gospodarki;Wysoki procent PKB sugeruje wysoki priorytet edukacji i zdolności podnoszenia przychodów wydatków publicznych.',
    'Należy pamiętać, że wydatki rządowe są niższe w niektórych krajach, w których sektor prywatny i / lub gospodarstwa domowe mają duży udział w całkowitym finansowaniu edukacji.',
    'Udział kobiet w decyzjach wykonanych we własnych gospodarstwach domowych, czyli gospodarstwa domowe, w których zwykle mieszkają z ich małżonkiem i / lub dzieci z innymi lub bez innych, są powszechnie akceptowane jako uniwersalny wskaźnik wzmocnienia kobiet.',
    'Zdolność kobiet do podejmowania decyzji, które wpływają na ich osobiste okoliczności, jest istotnym elementem ich wzmocnienia i służy jako ważnym czynnikiem przyczyniającym się do ich ogólnego rozwoju.',
    'Ten nierówny podział obowiązków jest skorelowany z różnicami płci w możliwościach gospodarczych, włączyć nisko żeński udział siły roboczej, segregację seksu zawodowego i rozpoznawania zarobków.',
    'Potrzeba równowagi płci w dystrybucji nieodpłatnej pracy krajowej i pielęgnacyjnej jest coraz bardziej uznawana, a cele zrównoważonego rozwoju rozwiązuje problem w celu 5.',
    'Wskaźniki śmiertelności dla różnych grup wiekowych (niemowlęta, dzieci, młodzież, młodzież i dorośli) i ogólne wskaźniki śmiertelności (średnia długość życia w urodzeniu lub przetrwanie w danym wieku) są ważnymi wskaźnikami stanu zdrowia w kraju.',
    'Ponieważ dane dotyczące częstości występowania i częstości występowania chorób są często niedostępne, wskaźniki śmiertelności są często używane do identyfikacji wrażliwych populacji i są wśród wskaźników najczęściej wykorzystywanych do porównania rozwoju społeczno-ekonomicznego w różnych krajach.',
    'Wskaźniki śmiertelności dla różnych grup wiekowych (niemowlęta, dzieci i dorośli) oraz ogólne wskaźniki śmiertelności (średnia długość życia w urodzeniu lub przetrwanie w danym wieku) są ważnymi wskaźnikami stanu zdrowia w kraju.',
    'Pomimo istnienia skutecznych leków i leczenia, HIV / AIDS jest nadal wiodącą przyczyną śmierci i zagrożenia dla zdrowia publicznego na świecie.',
    'Kraje o niskich i średnich dochodach nadal ponosi nieproporcjonalny udział w globalnym obciążeniu HIV / AIDS.',
    'Również identyfikacja nowo zakażonych osób pozwoli interwencji w celu zmniejszenia ryzyka transmisji HIV.',
    'Immunizacja jest jednym z najbardziej opłacalnych interwencji zdrowia publicznego, a jest niezbędnym składnikiem zmniejszania obniżenia śmiertelności.',
    'Szacunki zasięgu szczepionki są wykorzystywane do monitorowania pokrycia usług szczepień i prowadzących eliminację choroby i wysiłki eliminacji.',
    'Zanieczyszczenie powietrza jest jednym z największych zagrożeń środowiska dla zdrowia.',
    'Według Światowej Organizacji Zdrowia, łączone skutki zanieczyszczenia powietrza otoczenia (na zewnątrz) i powietrza domowego powodują około 7 milionów przedwczesnych zgonów każdego roku.',
    'Większość zgonów występuje ze względu na zwiększoną śmiertelność z udaru, choroby serca, przewlekłej obturacyjnej choroby płuc, raka płuc i ostre zakażenia oddechowe.',
    'Większość zgonów związanych z biegunami jest spowodowana odwodnieniem, a wiele z tych zgonów można zapobiec przy użyciu soli doustnych w domu.',
    'Wskaźniki śmiertelności z powodu niezamierzonego zatrucia pozostają stosunkowo wysokie w krajach o niskich dochodach.',
    'Niebezpieczna woda pitna, niebezpieczne sanitarne i brak higieny są ważnymi przyczynami śmierci.',
    'Większość zgonów biegunkowych na świecie jest spowodowana niebezpieczną wodą, sanitarną lub higieną.',
    'Dane dotyczące dystrybucji dochodów i współczynnik GINI mierzą nierówność w dochodach lub konsumpcji i ważnych wskaźnikach do pomiaru wspólnej dobrobytu.',
    'Cel proporcji Grupy Banku Światowego promowania wspólnego dobrobytu zostało zdefiniowane jako wspieranie wzrostu dochodów w wysokości 40 procent dystrybucji dobrobytu w każdym kraju.',
    'Zmniejszenie kosztów transakcji przelewu ma bezpośredni wpływ na rozwój, uwalniając dodatkowe zasoby, które zamiast płacić jako koszt transakcji, pozostanie z nadawcami i odbiornikami przepływów.',
    'Dobre odżywianie jest kamieniem węgielnym dla przetrwania, zdrowia i rozwoju.',
    'Surowy wskaźnik śmiertelności jest dobrym wskaźnikiem ogólnego stanu zdrowia obszaru geograficznego lub populacji.',
    'Wyższe surowe stawki śmiertelne można znaleźć w niektórych krajach rozwiniętych, pomimo wysokiej długości życia, ponieważ zazwyczaj te kraje mają znacznie wyższy odsetek osób starszych, ze względu na obniżone ostatnie wskaźniki urodzeń i niższych współczynników umieralności.',
    'Wzory rozwoju w kraju są częściowo określone przez kompozycję wieku swojej populacji.',
    'Różne grupy wiekowe mają różne skutki zarówno na środowisko, jak i na potrzeby infrastruktury.',
    'Dlatego struktura wiekowa populacji jest przydatna do analizy użytkowania zasobów i formułowanie przyszłych celów polityki i planowania w odniesieniu do infrastruktury i rozwoju.',
    'Ludność kobiet w stosunku do populacji męskiej jest głównym wskaźnikiem demograficznym, odzwierciedlającym wydarzenia historyczne, takie jak wojny i społeczno-demograficzne i etno-kulturowe cechy ludności.',
    'Zasadniczo miasta oferują bardziej korzystne ustawienie dotyczące rozwiązywania problemów społecznych i środowiskowych niż obszary wiejskie.',
    'Gospodarki o niskich i średnich dochodach są coraz ważniejszą częścią globalnego systemu handlowego.',
    'Chociaż integracja globalna wzrosła, gospodarki o niskich i średnich dochodach nadal stoją w obliczu barier handlowych podczas uzyskiwania dostępu do innych rynków.',
    'Stężenie dwutlenku węgla (CO2) w naszej atmosferze według stanu na lipiec 2021 roku jest najwyższe w historii ludzkości.',
    'Jedenaście procent wszystkich globalnych emisji gazów cieplarnianych spowodowanych przez ludzi jest spowodowanych wylesianiem — porównywalne z emisjami ze wszystkich samochodów osobowych na świecie.',
    'Lasy tropikalne są niezwykle skuteczne w magazynowaniu dwutlenku węgla, zapewniając co najmniej jedną trzecią działań łagodzących potrzebnych 7, aby zapobiec najgorszym scenariuszom związanym ze zmianą klimatu. Jednak rozwiązania oparte na przyrodzie otrzymują tylko 3% wszystkich środków na klimat.',
    'Rozwiązania dotyczące klimatu naturalnego, takie jak przywracanie zdegradowanych lasów, mogą stworzyć aż 39 miejsc pracy na milion wydanych dolarów — to wskaźnik tworzenia miejsc pracy ponad sześciokrotnie wyższy niż w przemyśle naftowym i gazowym.',
    'CO2 w naszej atmosferze jest bezwonny i bez smaku. Dzieje się tak, ponieważ jest w tak niskim stężeniu, że jesteśmy do niego przyzwyczajeni; ale jeśli zwiększysz ilość CO2 w powietrzu, zauważysz ostry kwaśny zapach i smak.',
    'Dwutlenek węgla jest używany do produkcji gazowanych napojów bezalkoholowych i wody gazowanej, takiej jak Coca-Cola. Jako gaz piwny, dwutlenek węgla jest zwykle używany do przesyłania piwa z beczek do kranów za pomocą dwutlenku węgla pod ciśnieniem.',
    'Dwutlenek węgla jest gazem osłonowym dla lasera CO2. Te lasery są zwykle dość duże, co utrudnia ich precyzyjne użycie, ale są bardzo mocne, co może być przydatne do cięcia grubego metalu.',
    'Ponad 1 milion gatunków jest zagrożonych wyginięciem z powodu zmiany klimatu.',
    'Każdej sekundy na świecie wyrzucanych jest 50 ton śmieci.',
    'Ustawione w szeregu ciężarówki wywożące rocznie 2,12 miliardów ton śmieci na wysypiska,  24 razy opasałyby kulę ziemską.',
    'Przeciętny Polak marnuje 235 kg żywności w ciągu roku.',
    '42% Polaków zdarza się wyrzucać żywność.',
    'Metan wytwarzany podczas rozkładu odpadów na wysypiskach stanowi 3-4% rocznej emisji gazów cieplarnianych.',
    'Metan pochłania promieniowanie podczerwone 60 razie bardziej niż dwutlenek węgla, który powszechnie uważa się za przyczynę „efektu cieplarnianego”.',
    'Do produkcji 1 tony papieru potrzeba ściąć około 17 drzew, które w ciągu roku produkują tlen dla 170 osób.',
    'Recykling makulatury to 65% oszczędność energii oraz 35% oszczędność wody w stosunku do procesów produkcji papieru z pierwotnych włókien celulozowych.',
    'Od początku produkcji przemysłowej tworzyw sztucznych wytworzono ich ok. 10 miliardów ton, jedynie 9% zostało poddane recyklingowi.',
    'Recykling 1 kg aluminium to oszczędność do 6 kg boksytu oraz do 14 kWh energii elektrycznej.',
    'Zużyte opakowania szklane można w nieskończoność przetapiać na nowe bez pogorszenia ich jakości, oszczędzając przy tym energię i chroniąc środowisko.',
    'Każdego roku na świecie od 5 do 13 mln ton tworzyw sztucznych, czyli od 1,5 do 4 % produkowanych plastików trafia do mórz i oceanów.',
    'Co 25 minut na naszej planecie ginie jeden gatunek zwierząt.',
    'Co roku liczba owadów na świecie malej o 2,5%.',
    'W ciągu minuty na świecie znika las o powierzchni równej 36 boiskom do piłki nożnej.',
    'Każdy z mieszkańców Polski zużywa około 150 litrów wody.',
    'Na świecie zużywanych jest łącznie około 22 trylionów kWh energii rocznie, z czego około ¼ przeznacza się na oświetlenie.',
    '1 litr zużytego oleju silnikowego może zanieczyścić 1 mln litrów wody.',
    '2/3 mieszkańców miast na świecie oddycha powietrzem zawierającym smog.',
    'Wokół Ziemi krąży około 19 tysięcy odpadów o wielkości do 10 cm i miliony mniejszej wielkości.',
    '75 procent zgonów następuje przedwcześnie wskutek zatrucia środowiska oraz niewłaściwego trybu życia.',
    'Wielka Plama Pacyficzna z odpadów plastiku zajmuje powierzchnię 1,6 mln km².',
    'Butelka PET rozkłada się w środowisku 1000 lat, szkło – 4000 lat, reklamówka – 400 lat, puszka aluminiowa – 150 lat, guma do żucia – 5 lat.',
    'Jeden hektar lasu liściastego może wyprodukować około 700 kg tlenu, co stanowi dobowe zapotrzebowanie ponad 2500 ludzi.',
    'W Polsce pracuje dziś 290 profesjonalnych elektrowni wiatrowych o łącznej mocy 10MW, podłączonych do sieci i sprzedających energię zakładom energetycznym. Razem produkują zaledwie 3% energii elektrycznej.',
    'Jeden nieszczelny, lekko kapiący kran powoduje, że w ciągu doby wycieka około 36 litrów wody. Nieszczelna spłuczka w WC powoduje wyciek w ciągu dnia około 720 litrów wody, a rocznie - 260m sześciennych wody.',
    'Aby wyprodukować jedną tonę papieru trzeba ściąć średnio 17 drzew.',
    'Jeżeli każdy z nas wyrzuci na śmietnik tylko jeden słoik to na wysypisko w całej Polsce trafi rocznie 10 000t szkła.',
    'W Polsce rocznie zużywa się 400 milionów aluminiowych puszek, które można powtórnie przetworzyć oraz wykorzystać i to nieskończenie wiele razy. Sześć puszek ze złomu to oszczędność energii równej spaleniu jednego litra paliwa.',
    'W Polsce tylko 222 tysiące ton odpadów komunalnych jest kompostowanych (2%). Dla porównania w Danii, Szwajcarii, Szwecji od 60%-80%.',
    'Każda szklana butelka ponownie wprowadzona do obiegu pozwala zaoszczędzić energię potrzebną do świecenia 100 watowej żarówki przez 4h.',
    'Według danych ONZ z 1988 roku aż 2/3 mieszkańców miast na świecie oddycha powietrzem zawierającym smog.',
    'Butelki, torebki śniadaniowe bądź torby na zakupy stanowią ok. 7% masy wszystkich śmieci, ale zajmują dużo miejsca, niemal 30% wszystkich odpadów.',
    'Jeden litr zużytego oleju silnikowego wylany do rzeki lub kanalizacji jest w stanie zanieczyścić 1 milion litrów wody!!!',
    'Metan, który się uwalnia z wysypisk śmieci jest 27 razy bardziej agresywny od dwutlenku węgla.',
    'W Polsce poziom selektywnego odzyskiwania odpadów wynosi jedynie 4 kg na mieszkańca, podczas gdy w Czechach jest to 19 kg, natomiast w Niemczech 76 kg na mieszkańca!',
    'Obecnie w Polsce wytwarzamy ok. 13.5mln ton odpadów komunalnych rocznie, co daje średnio daje 350kg na mieszkańca rocznie.',
    'Codziennie każde duże miasto w Polsce wysyła na składowisko 100 ciężarówek z odpadami.',
    'Każdy z nas wyrzuca w ciągu roku około 56 opakowań szklanych nadających się w pełni do ponownego wykorzystania .',
    'Produkty ze szkła w 100% nadają się do ponownego przerobu (recyklingu).',
    'Wyprodukowanie 6 puszek ze złomu aluminiowego daje oszczędność energii równoważną energii uzyskanej ze spalenia 1 litra benzyny.',
    'Ponowny przerób stosu gazet o wysokości 125cm pozwala na uratowanie sześciometrowej sosny. Wyprodukowanie 1 tony papieru wymaga ścięcia 17 drzew.',
    'Każda tona odzyskanej makulatury pozwoli zaoszczędzić 1200l wody w papierni oraz 2.5m3 przestrzeni środowiska.',
    'Każde 100kg papieru to średniej wielkości dwa drzewa, przy czym należy wiedzieć, że jedno drzewo produkuje w ciągu roku tlen wystarczający dla 10 osób.',
    'Około 2mln ptaków i ssaków wodnych ginie na świecie na skutek połknięcia plastikowych odpadów wrzucanych do mórz i oceanów.',
    'Ilość nagromadzonych odpadów zwiększyła się trzykrotnie przez ostatnie 20 lat. Zajmowana przez te odpady powierzchnia zwiększyła się dwukrotnie.',
];

const CuriosityDisplayer: FC = () => {
    return <div><span style={{color: 'grey'}}>ciekawostka:</span> {curiosities[Math.floor(Math.random()*curiosities.length)]}</div>
}

export default CuriosityDisplayer;